name: tax_collect
description: "A project which help government entities to operate tax collection operations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0
  adaptive_theme: ^3.6.0
  auto_route: ^8.2.0
  lottie: 3.1.0
  auto_size_text: ^3.0.0
  thermal_printer: ^1.0.5
  responsive_grid: ^2.4.4
  responsive_framework: ^1.4.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.2.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  copy_with_extension: ^5.0.4
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.3
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  loading_animation_widget: ^1.2.1
  either_dart: ^1.0.0
  gap: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.3.0
  dio: ^5.4.3+1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  pretty_dio_logger: ^1.3.1
  path: ^1.9.0
  package_info_plus: ^8.0.0
  cached_network_image: ^3.3.1
  flutter_infinite_marquee: ^1.0.0
  intl: any
  flutter_svg: ^2.0.10+1
  timeago: ^3.6.1
  formz: ^0.7.0
  #dart run rename setAppName --value "Tax Collect"
  #dart run rename setBundleId --value "com.evolverdc.taxcollect"
  rename: ^3.0.2
  # dart run easy_localization:generate -S lib/core/config/localization -o locale_keys.g.dart -f keys
  easy_localization: ^3.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^8.0.0
  copy_with_extension_gen: ^5.0.4
  drift_dev: ^2.18.0
  json_serializable: ^6.8.0
  analyzer: any
  retrofit_generator: ^8.1.0
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/lottieFile/
    - lib/core/config/localization/

# configuration of flutter
flutter_gen:
  output: lib/generated/ # Optional (default: lib/gen/)
  line_length: 90 # Optional (default: 80)

  # Optional
  integrations:
  flutter_svg: true
  lottie: true
  #flare_flutter: true
  #rive: true

#use: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/tax.png
  color_dark: "#222201"
  image_dark: assets/images/tax.png

#use: dart run flutter_launcher_icons
flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/images/tax.png
  image_path: assets/images/tax.png
  ios: true
  image_path_ios: assets/images/tax.png
  remove_alpha_ios: true
  web:
    generate: true
    image_path: assets/images/tax.png
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: assets/images/tax.png
  macos:
    generate: true
    image_path: assets/images/tax.png